<a href="https://colab.research.google.com/github/SieDeta/preprocessing/blob/main/preprocessingSJY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('datapemilukpu.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [ ]:
print(x)

[['HATI NURANI RAKYAT ' 1.0 18578.0 1.0 1.0 594.0]
 ['HATI NURANI RAKYAT ' 1.0 18578.0 1.0 1.0 943.0]
 ['HATI NURANI RAKYAT ' 1.0 18578.0 nan 1.0 1730.0]
 ...
 ['PARTAI BURUH' 44.0 11003.0 1.0 6.0 72.0]
 ['PARTAI BURUH' 44.0 11003.0 1.0 6.0 52.0]
 ['PARTAI BURUH' 44.0 11003.0 1.0 6.0 397.0]]


In [ ]:
print(y)

['TIDAK' 'TIDAK' 'TIDAK' 'YA' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK'
 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK'
 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK'
 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK'
 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK'
 'TIDAK' 'YA' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK'
 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK'
 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'YA' 'TIDAK'
 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK'
 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK'
 'YA' 'TIDAK' 'TIDAK' 'TIDAK' 'YA' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK'
 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'YA' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK'
 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'YA'
 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'TIDAK' 'YA' 'TIDAK' 'T

In [ ]:
print(dataset.columns)
print(dataset.dtypes)

Index(['NAMA PARTAI POLITIK', 'NO.URUT PARPOL', 'SUARA SAH PARTAI',
       'JUML.PEROLEHAN KURSI', 'DAERAH PEMILIHAN', 'SUARA SAH CALEG',
       'TERPILIH ATAU TIDAK'],
      dtype='object')
NAMA PARTAI POLITIK      object
NO.URUT PARPOL          float64
SUARA SAH PARTAI        float64
JUML.PEROLEHAN KURSI    float64
DAERAH PEMILIHAN        float64
SUARA SAH CALEG         float64
TERPILIH ATAU TIDAK      object
dtype: object


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 3:8])
x[:, 3:8] = imputer.transform(x[:, 3:8])

In [ ]:
print(x)

[['HATI NURANI RAKYAT ' 1.0 18578.0 1.0 1.0 594.0]
 ['HATI NURANI RAKYAT ' 1.0 18578.0 1.0 1.0 943.0]
 ['HATI NURANI RAKYAT ' 1.0 18578.0 4.629353233830845 1.0 1730.0]
 ...
 ['PARTAI BURUH' 44.0 11003.0 1.0 6.0 72.0]
 ['PARTAI BURUH' 44.0 11003.0 1.0 6.0 52.0]
 ['PARTAI BURUH' 44.0 11003.0 1.0 6.0 397.0]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')

# Ubah matriks sparse ke matriks padat menggunakan .toarray()
x = ct.fit_transform(x.toarray())

In [ ]:
print(x)

  (0, 0)	1.0
  (0, 30)	1.0
  (0, 31)	18578.0
  (0, 32)	1.0
  (0, 33)	1.0
  (0, 34)	594.0
  (1, 0)	1.0
  (1, 30)	1.0
  (1, 31)	18578.0
  (1, 32)	1.0
  (1, 33)	1.0
  (1, 34)	943.0
  (2, 0)	1.0
  (2, 30)	1.0
  (2, 31)	18578.0
  (2, 32)	4.629353233830845
  (2, 33)	1.0
  (2, 34)	1730.0
  (3, 0)	1.0
  (3, 30)	1.0
  (3, 31)	18578.0
  (3, 32)	4.629353233830845
  (3, 33)	1.0
  (3, 34)	2508.0
  (4, 0)	1.0
  :	:
  (420, 34)	402.0
  (421, 5)	1.0
  (421, 30)	44.0
  (421, 31)	11003.0
  (421, 32)	1.0
  (421, 33)	6.0
  (421, 34)	3065.0
  (422, 5)	1.0
  (422, 30)	44.0
  (422, 31)	11003.0
  (422, 32)	1.0
  (422, 33)	6.0
  (422, 34)	72.0
  (423, 5)	1.0
  (423, 30)	44.0
  (423, 31)	11003.0
  (423, 32)	1.0
  (423, 33)	6.0
  (423, 34)	52.0
  (424, 5)	1.0
  (424, 30)	44.0
  (424, 31)	11003.0
  (424, 32)	1.0
  (424, 33)	6.0
  (424, 34)	397.0


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print (y)

[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0
 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
 1 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 1
 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1
 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 1)

In [ ]:
print(x_train)

[[1.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  2.00000000e+00 2.14300000e+03]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 ... 5.00000000e+00
  3.56521739e+00 1.59000000e+02]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 ... 1.30000000e+01
  4.00000000e+00 2.17300000e+03]
 ...
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  2.00000000e+00 1.66900000e+03]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 ... 6.00000000e+00
  2.00000000e+00 4.25000000e+02]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  5.00000000e+00 1.08391940e+03]]


In [ ]:
print(x_test)

[[1.000e+00 0.000e+00 0.000e+00 ... 8.000e+00 3.000e+00 2.951e+03]
 [1.000e+00 0.000e+00 0.000e+00 ... 5.000e+00 1.000e+00 3.380e+02]
 [1.000e+00 0.000e+00 0.000e+00 ... 5.000e+00 6.000e+00 1.260e+02]
 ...
 [1.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 6.000e+00 2.200e+01]
 [1.000e+00 0.000e+00 0.000e+00 ... 5.000e+00 2.000e+00 5.050e+02]
 [1.000e+00 0.000e+00 0.000e+00 ... 1.000e+00 2.000e+00 3.149e+03]]


In [ ]:
print(y_train)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 1 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 1 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0]


In [ ]:
print(y_test)

[0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [ ]:
print(x_train)

[[ 1.          0.          0.         ... -1.12439987 -0.94087728
   0.99977301]
 [ 1.          0.          0.         ...  0.07235704  0.02981877
  -0.74044837]
 [ 1.          0.          0.         ...  1.98716809  0.29945656
   1.02608684]
 ...
 [ 1.          0.          0.         ... -1.12439987 -0.94087728
   0.58401447]
 [ 1.          0.          0.         ...  0.31170842 -0.94087728
  -0.5071324 ]
 [ 1.          0.          0.         ... -1.12439987  0.91962347
   0.07082406]]


In [ ]:
print(x_test)

[[ 1.          0.          0.         ...  0.79041118 -0.32071036
   1.7084922 ]
 [ 1.          0.          0.         ...  0.07235704 -1.56104419
  -0.58344251]
 [ 1.          0.          0.         ...  0.07235704  1.53979039
  -0.76939359]
 ...
 [ 1.          0.          0.         ... -1.12439987  1.53979039
  -0.86061487]
 [ 1.          0.          0.         ...  0.07235704 -0.94087728
  -0.43696218]
 [ 1.          0.          0.         ... -0.88504849 -0.94087728
   1.88216348]]
